# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72fb65c12e7bf935a7f3b7b44d7cd08b11a91d77ff1bee7de571ee1426e0c2f65324e48bcfa20b6bd6426f81bed56c93ebc3cef1b88110d4bc70490071a2a946

test:
  secret_key_base: be1a46c124c7e1356671f3a1bc893d608c84ce366b0786ec6df47e42cb5c8c992476682d8fdb731b4f04b073eefc2dc26939535854e5ff99a3f0ca7d3be20065

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
